### PR TITLE
Add MQTT to list of targets for BTMon data.

### PR DESCRIPTION
**Pull request by mrguessed**
Enable the publication of Feed data to MQTT.  Full details inside `btmon.py`

Signed-off-by: Mark Clark mr.guessed@gmail.com

### CODE REVIEW

**Comment by mrguessed** [comment]
@matthewwall Do you need me to add anything else before PR merge?

**Comment by matthewwall** [comment]
hi mark, i just need some time to test.  i was going to test your changes on a gem i installed at the beginning of april, but ran out of time.  i'll be back on that site mid-may and will test then.  sorry to take so long.  m

**Comment by mrguessed** [comment]
No worries, just wanted to ensure I hadn't missed something in the submission.  I'm looking at making a direct connect to InfluxDB also

**Comment by matthewwall** [comment]
i did an influx extension for weewx - i've been running it for a few weeks before making it public.  it should be pretty easy to do it for btmon too. the hardest part is figuring out how to structure the data from the influx point of view - database vs measurement vs tag vs value.

**Comment by mrguessed** [comment]
Thanks, I'll take a look at that when I'm closer.

I was planning on mimicking the style that @InfluxData uses with their MQTT plugin in their Telegraf component.  That way, folks could easily move between the two models which too much data-massaging/re-ETL processing.

**Comment by roscoe57** [comment]
Looking to fire ECM data into InfluxDB, would probably prefer direct rather than MQTT.
Thought it was worth asking if anyone got round to it ? before I crack on.

**Comment by mrguessed** [comment]
Sorry @roscoe57, I missed this earlier post.  Looks like @chicago6061 may have filed a version in [my repo](https://github.com/mrguessed/btmon/pull/1), I've directed him to redo the PR here.

Perhaps you can work together on evolving his proposal.

**Comment by mroch** [comment]
@matthewwall @mrguessed i wrote up some thoughts on influxdb data structure in #5. wanna continue the influxdb discussion there to unblock this MQTT PR?

**Comment by matthewwall** [comment]
the mqtt changes have been added to matthewwall:master with a bump to btmon version 3.2.0

**Comment by mrguessed** [comment]
Thanks!

**Comment by ghost** [comment]
btmon MQTT working great. Thanks!

**Comment by mrguessed** [comment]
@tgmaxx Glad you like it.  It's getting a workout in my house ;)

**Pull request closed without merging**
